(define (problem p19) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 0)
    (= (turbine_eoliche) 0)
    (= (dighe_idrauliche) 0)
    (= (reattori_geotermici) 0)
    (= (operatori_impianto) 0)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 2)
    (= (soglia_eolico) 3)
    (= (soglia_idraulico) 80)
    (= (soglia_geotermico) 150)
    (= (soglia_ibrido) 999)
    (= (rate_solare) 3)
    (= (rate_eolico) 10)
    (= (rate_idraulico) 3000)
    (= (rate_geotermico) 8000)
    (= (rate_ibrido) 1)
)
(:goal (and (>= (energia_prodotta) 100000)))
)
