(define (problem p12) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 0)
    (= (turbine_eoliche) 0)
    (= (dighe_idrauliche) 0)
    (= (reattori_geotermici) 0)
    (= (operatori_impianto) 0)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 1)
    (= (soglia_eolico) 3)
    (= (soglia_idraulico) 999)
    (= (soglia_geotermico) 25)
    (= (soglia_ibrido) 999)
    (= (rate_solare) 2)
    (= (rate_eolico) 10)
    (= (rate_idraulico) 1)
    (= (rate_geotermico) 1000)
    (= (rate_ibrido) 1)
)
(:goal (and (>= (energia_prodotta) 5000)))
)
