(define (problem p15) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 0)
    (= (turbine_eoliche) 0)
    (= (dighe_idrauliche) 2)
    (= (reattori_geotermici) 3)
    (= (operatori_impianto) 0)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 1)
    (= (soglia_eolico) 999)
    (= (soglia_idraulico) 5)
    (= (soglia_geotermico) 10)
    (= (soglia_ibrido) 999)
    (= (rate_solare) 3)
    (= (rate_eolico) 1)
    (= (rate_idraulico) 100)
    (= (rate_geotermico) 300)
    (= (rate_ibrido) 1)
)
(:goal (and (>= (energia_prodotta) 2000)))
)
