(define (problem p10) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 0)
    (= (turbine_eoliche) 0)
    (= (dighe_idrauliche) 0)
    (= (reattori_geotermici) 0)
    (= (operatori_impianto) 0)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 999)
    (= (soglia_eolico) 1)
    (= (soglia_idraulico) 30)
    (= (soglia_geotermico) 999)
    (= (soglia_ibrido) 999)
    (= (rate_solare) 1)
    (= (rate_eolico) 2)
    (= (rate_idraulico) 800)
    (= (rate_geotermico) 1)
    (= (rate_ibrido) 1)
)
(:goal (and (>= (energia_prodotta) 4000)))
)
