(define (problem p14) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 0)
    (= (turbine_eoliche) 4)
    (= (dighe_idrauliche) 0)
    (= (reattori_geotermici) 0)
    (= (operatori_impianto) 6)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 999)
    (= (soglia_eolico) 8)
    (= (soglia_idraulico) 999)
    (= (soglia_geotermico) 20)
    (= (soglia_ibrido) 999)
    (= (rate_solare) 1)
    (= (rate_eolico) 30)
    (= (rate_idraulico) 1)
    (= (rate_geotermico) 600)
    (= (rate_ibrido) 1)
)
(:goal (and (>= (energia_prodotta) 3000)))
)
