(define (problem p13) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 5)
    (= (turbine_eoliche) 0)
    (= (dighe_idrauliche) 0)
    (= (reattori_geotermici) 0)
    (= (operatori_impianto) 0)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 6)
    (= (soglia_eolico) 999)
    (= (soglia_idraulico) 999)
    (= (soglia_geotermico) 999)
    (= (soglia_ibrido) 15)
    (= (rate_solare) 8)
    (= (rate_eolico) 1)
    (= (rate_idraulico) 1)
    (= (rate_geotermico) 1)
    (= (rate_ibrido) 200)
)
(:goal (and (>= (energia_prodotta) 1000)))
)
