(define (problem p20) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 0)
    (= (turbine_eoliche) 0)
    (= (dighe_idrauliche) 0)
    (= (reattori_geotermici) 0)
    (= (operatori_impianto) 0)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 1)
    (= (soglia_eolico) 2)
    (= (soglia_idraulico) 300)
    (= (soglia_geotermico) 500)
    (= (soglia_ibrido) 200)
    (= (rate_solare) 1)
    (= (rate_eolico) 5)
    (= (rate_idraulico) 50000)
    (= (rate_geotermico) 80000)
    (= (rate_ibrido) 30000)
)
(:goal (and (>= (energia_prodotta) 1000000)))
)
