(define (problem p16) (:domain energia)
(:objects )
(:init
    (= (pannelli_solari) 8)
    (= (turbine_eoliche) 0)
    (= (dighe_idrauliche) 0)
    (= (reattori_geotermici) 0)
    (= (operatori_impianto) 3)
    (= (energia_prodotta) 0)
    (= (soglia_solare) 10)
    (= (soglia_eolico) 2)
    (= (soglia_idraulico) 999)
    (= (soglia_geotermico) 15)
    (= (soglia_ibrido) 20)
    (= (rate_solare) 20)
    (= (rate_eolico) 5)
    (= (rate_idraulico) 1)
    (= (rate_geotermico) 500)
    (= (rate_ibrido) 1000)
)
(:goal (and (>= (energia_prodotta) 8000)))
)
