(define (problem p17) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 10)
    (= (soglia_compostaggio) 10)
    (= (soglia_recupero_a) 20)
    (= (soglia_recupero_b) 18)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 1)
    (= (rate_compostaggio) 1)
    (= (rate_recupero) 2)
)
(:goal (and (>= (rifiuti_smaltiti) 290)
            (>= (energia_recuperata) 80)
            (>= (compost) 75)))
)
