(define (problem p19) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 13)
    (= (soglia_compostaggio) 13)
    (= (soglia_recupero_a) 18)
    (= (soglia_recupero_b) 18)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 1)
    (= (rate_compostaggio) 1)
    (= (rate_recupero) 1)
)
(:goal (and (>= (rifiuti_smaltiti) 700)))
)