(define (problem p10) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 5)
    (= (soglia_compostaggio) 5)
    (= (soglia_recupero_a) 5)
    (= (soglia_recupero_b) 5)
    (= (rate_raccolta) 2)
    (= (rate_incenerimento) 3)
    (= (rate_compostaggio) 3)
    (= (rate_recupero) 2)
)
(:goal (and (>= (rifiuti_smaltiti) 180)))
)