(define (problem p13) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 7)
    (= (soglia_compostaggio) 7)
    (= (soglia_recupero_a) 14)
    (= (soglia_recupero_b) 12)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 1)
    (= (rate_compostaggio) 2)
    (= (rate_recupero) 3)
)
(:goal (and (>= (rifiuti_smaltiti) 170)
            (>= (energia_recuperata) 45)
            (>= (compost) 40)))
)
