(define (problem p13) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 6)
    (= (soglia_compostaggio) 6)
    (= (soglia_recupero_a) 8)
    (= (soglia_recupero_b) 8)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 2)
    (= (rate_compostaggio) 2)
    (= (rate_recupero) 2)
)
(:goal (and (>= (rifiuti_smaltiti) 300)))
)