(define (problem p16) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 9)
    (= (soglia_compostaggio) 9)
    (= (soglia_recupero_a) 18)
    (= (soglia_recupero_b) 15)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 1)
    (= (rate_compostaggio) 1)
    (= (rate_recupero) 2)
)
(:goal (and (>= (rifiuti_smaltiti) 250)
            (>= (energia_recuperata) 70)
            (>= (compost) 65)))
)
