(define (problem p16) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 9)
    (= (soglia_compostaggio) 9)
    (= (soglia_recupero_a) 12)
    (= (soglia_recupero_b) 12)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 2)
    (= (rate_compostaggio) 2)
    (= (rate_recupero) 1)
)
(:goal (and (>= (rifiuti_smaltiti) 450)))
)