(define (problem p02) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 999)
    (= (soglia_compostaggio) 999)
    (= (soglia_recupero_a) 999)
    (= (soglia_recupero_b) 999)
    (= (rate_raccolta) 2)
    (= (rate_incenerimento) 1)
    (= (rate_compostaggio) 1)
    (= (rate_recupero) 1)
)
(:goal (and (>= (rifiuti_smaltiti) 20)))
)