(define (problem p08) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 5)
    (= (soglia_compostaggio) 5)
    (= (soglia_recupero_a) 10)
    (= (soglia_recupero_b) 8)
    (= (rate_raccolta) 2)
    (= (rate_incenerimento) 2)
    (= (rate_compostaggio) 2)
    (= (rate_recupero) 3)
)
(:goal (and (>= (rifiuti_smaltiti) 70)
            (>= (energia_recuperata) 15)
            (>= (compost) 10)))
)
