(define (problem p14) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 8)
    (= (soglia_compostaggio) 8)
    (= (soglia_recupero_a) 16)
    (= (soglia_recupero_b) 14)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 1)
    (= (rate_compostaggio) 1)
    (= (rate_recupero) 3)
)
(:goal (and (>= (rifiuti_smaltiti) 190)
            (>= (energia_recuperata) 50)
            (>= (compost) 45)))
)
