(define (problem p10) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 6)
    (= (soglia_compostaggio) 6)
    (= (soglia_recupero_a) 12)
    (= (soglia_recupero_b) 10)
    (= (rate_raccolta) 2)
    (= (rate_incenerimento) 2)
    (= (rate_compostaggio) 2)
    (= (rate_recupero) 3)
)
(:goal (and (>= (rifiuti_smaltiti) 110)
            (>= (energia_recuperata) 25)
            (>= (compost) 25)))
)
