(define (problem p10) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (vetro_raccolta) 0)
    (= (metallo_raccolta) 0)
    (= (materiale_riciclato) 0)
    (= (inquinamento) 0)
    (= (capacita_impianto) 5)
    (= (soglia_incenerimento) 13)
    (= (soglia_compostaggio) 13)
    (= (soglia_recupero_a) 18)
    (= (soglia_recupero_b) 18)
    (= (soglia_fusione_a) 13)
    (= (soglia_fusione_b) 14)
    (= (soglia_riciclo_a) 24)
    (= (soglia_riciclo_b) 7)
    (= (soglia_manutenzione) 14)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 2)
    (= (rate_compostaggio) 2)
    (= (rate_recupero) 3)
    (= (rate_fusione) 2)
    (= (rate_riciclo_avanzato) 10)
    (= (rate_raccolta_differenziata) 3)
)
(:goal (and (>= (rifiuti_smaltiti) 550)))
)