(define (problem p20) (:domain riciclo)
(:objects )
(:init
    (= (carta_raccolta) 0)
    (= (plastica_raccolta) 0)
    (= (energia_recuperata) 0)
    (= (compost) 0)
    (= (rifiuti_smaltiti) 0)
    (= (soglia_incenerimento) 15)
    (= (soglia_compostaggio) 15)
    (= (soglia_recupero_a) 25)
    (= (soglia_recupero_b) 25)
    (= (rate_raccolta) 1)
    (= (rate_incenerimento) 1)
    (= (rate_compostaggio) 1)
    (= (rate_recupero) 1)
)
(:goal (and (>= (rifiuti_smaltiti) 450)
            (>= (energia_recuperata) 120)
            (>= (compost) 110)
            (>= (carta_raccolta) 50)
            (>= (plastica_raccolta) 50)))
)
