(define (problem p12) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 10)
    (= (soglia_imballaggio) 10)
    (= (soglia_etichettatura) 10)
    (= (soglia_refrigerazione) 5)
    (= (soglia_veicoli) 10)
    (= (rate_automatica) 300)
    (= (rate_express) 300)
    (= (rate_frigo) 50)
)
(:goal (and (>= (pacchi_spediti) 10000)))
)
