(define (problem p01) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 1)
    (= (soglia_imballaggio) 1)
    (= (soglia_etichettatura) 1)
    (= (soglia_refrigerazione) 1)
    (= (soglia_veicoli) 1)
    (= (rate_automatica) 100)
    (= (rate_express) 50)
    (= (rate_frigo) 30)
)
(:goal (and (>= (pacchi_spediti) 500)))
)
