(define (problem p19) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 100)
    (= (soglia_imballaggio) 100)
    (= (soglia_etichettatura) 60)
    (= (soglia_refrigerazione) 40)
    (= (soglia_veicoli) 30)
    (= (rate_automatica) 700)
    (= (rate_express) 500)
    (= (rate_frigo) 300)
)
(:goal (and (>= (pacchi_spediti) 1000000)))
)
