(define (problem p13) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 50)
    (= (soglia_imballaggio) 50)
    (= (soglia_etichettatura) 20)
    (= (soglia_refrigerazione) 5)
    (= (soglia_veicoli) 15)
    (= (rate_automatica) 600)
    (= (rate_express) 250)
    (= (rate_frigo) 60)
)
(:goal (and (>= (pacchi_spediti) 50000)))
)
