(define (problem p18) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 25)
    (= (setup_imballaggio) 25)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 20)
    (= (soglia_imballaggio) 20)
    (= (soglia_etichettatura) 15)
    (= (soglia_refrigerazione) 10)
    (= (soglia_veicoli) 8)
    (= (rate_automatica) 350)
    (= (rate_express) 280)
    (= (rate_frigo) 150)
)
(:goal (and (>= (pacchi_spediti) 25000)))
)
