(define (problem p20) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 500)
    (= (soglia_imballaggio) 500)
    (= (soglia_etichettatura) 200)
    (= (soglia_refrigerazione) 150)
    (= (soglia_veicoli) 100)
    (= (rate_automatica) 11)
    (= (rate_express) 10)
    (= (rate_frigo) 9)
)
(:goal (and (>= (pacchi_spediti) 100000)))
)
