(define (problem p14) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 8)
    (= (setup_imballaggio) 5)
    (= (setup_etichettatura) 12)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 3)
    (= (personale) 2)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 15)
    (= (soglia_imballaggio) 15)
    (= (soglia_etichettatura) 15)
    (= (soglia_refrigerazione) 8)
    (= (soglia_veicoli) 8)
    (= (rate_automatica) 400)
    (= (rate_express) 350)
    (= (rate_frigo) 120)
)
(:goal (and (>= (pacchi_spediti) 20000)))
)
