(define (problem p15) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 300)
    (= (soglia_imballaggio) 300)
    (= (soglia_etichettatura) 150)
    (= (soglia_refrigerazione) 100)
    (= (soglia_veicoli) 80)
    (= (rate_automatica) 800)
    (= (rate_express) 400)
    (= (rate_frigo) 200)
)
(:goal (and (>= (pacchi_spediti) 500000)))
)
