(define (problem p11) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 5)
    (= (soglia_imballaggio) 5)
    (= (soglia_etichettatura) 3)
    (= (soglia_refrigerazione) 3)
    (= (soglia_veicoli) 2)
    (= (rate_automatica) 1000)
    (= (rate_express) 50)
    (= (rate_frigo) 20)
)
(:goal (and (>= (pacchi_spediti) 5000)))
)
