(define (problem p09) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 250)
    (= (soglia_imballaggio) 250)
    (= (soglia_etichettatura) 100)
    (= (soglia_refrigerazione) 80)
    (= (soglia_veicoli) 50)
    (= (rate_automatica) 500)
    (= (rate_express) 200)
    (= (rate_frigo) 100)
)
(:goal (and (>= (pacchi_spediti) 50000)))
)
