(define (problem p16) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 30)
    (= (soglia_imballaggio) 30)
    (= (soglia_etichettatura) 20)
    (= (soglia_refrigerazione) 3)
    (= (soglia_veicoli) 10)
    (= (rate_automatica) 200)
    (= (rate_express) 150)
    (= (rate_frigo) 900)
)
(:goal (and (>= (pacchi_spediti) 30000)))
)
