(define (problem p05) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 10)
    (= (soglia_imballaggio) 10)
    (= (soglia_etichettatura) 5)
    (= (soglia_refrigerazione) 5)
    (= (soglia_veicoli) 3)
    (= (rate_automatica) 200)
    (= (rate_express) 100)
    (= (rate_frigo) 80)
)
(:goal (and (>= (pacchi_spediti) 2000)))
)
