(define (problem p17) (:domain logistica)
(:objects )
(:init
    (= (setup_smistamento) 0)
    (= (setup_imballaggio) 0)
    (= (setup_etichettatura) 0)
    (= (setup_refrigerazione) 0)
    (= (veicoli) 0)
    (= (personale) 0)
    (= (pacchi_spediti) 0)
    (= (soglia_smistamento) 40)
    (= (soglia_imballaggio) 40)
    (= (soglia_etichettatura) 30)
    (= (soglia_refrigerazione) 25)
    (= (soglia_veicoli) 20)
    (= (rate_automatica) 500)
    (= (rate_express) 400)
    (= (rate_frigo) 300)
)
(:goal (and (>= (pacchi_spediti) 8000)))
)
