(define (problem p09) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 3)
    (= (soglia_assemblaggio) 5)
    (= (soglia_qualita) 6)
    (= (soglia_spedizione) 10)
    (= (soglia_ottimizzazione) 999)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 2)
    (= (rate_spedizione) 2)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 60)
            (>= (qualita) 12)
            (>= (spedizioni) 8)
            (>= (scorte_energia) 5)))
)
