(define (problem p07) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 3)
    (= (soglia_assemblaggio) 4)
    (= (soglia_qualita) 5)
    (= (soglia_spedizione) 999)
    (= (soglia_ottimizzazione) 999)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 3)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 45)
            (>= (qualita) 8)
            (>= (semilavorati) 6)))
)
