(define (problem p17) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 6)
    (= (soglia_assemblaggio) 10)
    (= (soglia_qualita) 15)
    (= (soglia_spedizione) 22)
    (= (soglia_ottimizzazione) 12)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 1)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 230)
            (>= (qualita) 50)
            (>= (spedizioni) 34)
            (>= (scorte_energia) 32)
            (>= (semilavorati) 24)
            (>= (materie_prime) 18)))
)
