(define (problem p20) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 10)
    (= (soglia_assemblaggio) 15)
    (= (soglia_qualita) 25)
    (= (soglia_spedizione) 35)
    (= (soglia_ottimizzazione) 20)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 1)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 400)
            (>= (qualita) 90)
            (>= (spedizioni) 60)
            (>= (scorte_energia) 55)
            (>= (semilavorati) 40)
            (>= (materie_prime) 30)))
)
