(define (problem p10) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 3)
    (= (soglia_assemblaggio) 5)
    (= (soglia_qualita) 6)
    (= (soglia_spedizione) 10)
    (= (soglia_ottimizzazione) 5)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 2)
    (= (rate_spedizione) 2)
    (= (rate_ottimizzazione) 2)
)
(:goal (and (>= (prodotti_finiti) 75)
            (>= (qualita) 15)
            (>= (spedizioni) 10)
            (>= (scorte_energia) 8)
            (>= (semilavorati) 8)))
)
