(define (problem p18) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 7)
    (= (soglia_assemblaggio) 12)
    (= (soglia_qualita) 18)
    (= (soglia_spedizione) 25)
    (= (soglia_ottimizzazione) 15)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 1)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 280)
            (>= (qualita) 60)
            (>= (spedizioni) 40)
            (>= (scorte_energia) 38)
            (>= (semilavorati) 28)
            (>= (materie_prime) 22)))
)
