(define (problem p13) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 5)
    (= (soglia_assemblaggio) 7)
    (= (soglia_qualita) 10)
    (= (soglia_spedizione) 15)
    (= (soglia_ottimizzazione) 8)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 1)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 2)
)
(:goal (and (>= (prodotti_finiti) 120)
            (>= (qualita) 28)
            (>= (spedizioni) 18)
            (>= (scorte_energia) 15)
            (>= (semilavorati) 14)))
)
