(define (problem p16) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 6)
    (= (soglia_assemblaggio) 9)
    (= (soglia_qualita) 14)
    (= (soglia_spedizione) 20)
    (= (soglia_ottimizzazione) 12)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 1)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 190)
            (>= (qualita) 40)
            (>= (spedizioni) 28)
            (>= (scorte_energia) 26)
            (>= (semilavorati) 20)
            (>= (materie_prime) 15)))
)
