(define (problem p01) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 1)
    (= (soglia_assemblaggio) 999)
    (= (soglia_qualita) 999)
    (= (soglia_spedizione) 999)
    (= (soglia_ottimizzazione) 999)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 100)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 5)))
)
