(define (problem p19) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 8)
    (= (soglia_assemblaggio) 12)
    (= (soglia_qualita) 20)
    (= (soglia_spedizione) 28)
    (= (soglia_ottimizzazione) 15)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 1)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 330)
            (>= (qualita) 70)
            (>= (spedizioni) 48)
            (>= (scorte_energia) 44)
            (>= (semilavorati) 32)
            (>= (materie_prime) 26)))
)
