(define (problem p15) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 5)
    (= (soglia_assemblaggio) 8)
    (= (soglia_qualita) 12)
    (= (soglia_spedizione) 18)
    (= (soglia_ottimizzazione) 10)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 1)
    (= (rate_spedizione) 1)
    (= (rate_ottimizzazione) 1)
)
(:goal (and (>= (prodotti_finiti) 160)
            (>= (qualita) 36)
            (>= (spedizioni) 24)
            (>= (scorte_energia) 22)
            (>= (semilavorati) 18)
            (>= (materie_prime) 12)))
)
