(define (problem p11) (:domain fabbrica)
(:objects )
(:init
    (= (materie_prime) 0)
    (= (semilavorati) 0)
    (= (prodotti_finiti) 0)
    (= (scorte_energia) 0)
    (= (qualita) 0)
    (= (spedizioni) 0)
    (= (costi_operativi) 0)
    (= (soglia_lavorazione) 4)
    (= (soglia_assemblaggio) 6)
    (= (soglia_qualita) 8)
    (= (soglia_spedizione) 12)
    (= (soglia_ottimizzazione) 6)
    (= (rate_lavorazione) 1)
    (= (rate_assemblaggio) 2)
    (= (rate_spedizione) 2)
    (= (rate_ottimizzazione) 2)
)
(:goal (and (>= (prodotti_finiti) 90)
            (>= (qualita) 20)
            (>= (spedizioni) 14)
            (>= (scorte_energia) 10)
            (>= (semilavorati) 10)))
)
