(define (problem p10) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 500)
    (= (soglia_bus) 100)
    (= (soglia_bici) 80)
    (= (soglia_tram) 50)
    (= (rate_metro) 500)
    (= (rate_bus) 50)
    (= (rate_bici) 20)
    (= (rate_tram) 200)
)
(:goal (and (>= (persone_trasportate) 200000)))
)
