(define (problem p14) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 100)
    (= (soglia_bus) 80)
    (= (soglia_bici) 2)
    (= (soglia_tram) 60)
    (= (rate_metro) 500)
    (= (rate_bus) 25)
    (= (rate_bici) 50)
    (= (rate_tram) 100)
)
(:goal (and (>= (persone_trasportate) 800)))
)
