(define (problem p11) (:domain traffico)
(:objects )
(:init
    (= (binari) 3)
    (= (corsie) 2)
    (= (piste_ciclabili) 0)
    (= (fermate) 1)
    (= (personale_atm) 2)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 8)
    (= (soglia_bus) 5)
    (= (soglia_bici) 4)
    (= (soglia_tram) 3)
    (= (rate_metro) 80)
    (= (rate_bus) 15)
    (= (rate_bici) 8)
    (= (rate_tram) 40)
)
(:goal (and (>= (persone_trasportate) 500)))
)
