(define (problem p04) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 5)
    (= (soglia_bus) 5)
    (= (soglia_bici) 5)
    (= (soglia_tram) 3)
    (= (rate_metro) 100)
    (= (rate_bus) 10)
    (= (rate_bici) 5)
    (= (rate_tram) 50)
)
(:goal (and (>= (persone_trasportate) 1000)))
)
