(define (problem p09) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 100)
    (= (soglia_bus) 50)
    (= (soglia_bici) 40)
    (= (soglia_tram) 20)
    (= (rate_metro) 500)
    (= (rate_bus) 50)
    (= (rate_bici) 20)
    (= (rate_tram) 200)
)
(:goal (and (>= (persone_trasportate) 50000)))
)
