(define (problem p02) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 2)
    (= (soglia_bus) 2)
    (= (soglia_bici) 2)
    (= (soglia_tram) 2)
    (= (rate_metro) 50)
    (= (rate_bus) 5)
    (= (rate_bici) 2)
    (= (rate_tram) 20)
)
(:goal (and (>= (persone_trasportate) 200)))
)
