(define (problem p13) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 5)
    (= (soglia_bus) 200)
    (= (soglia_bici) 50)
    (= (soglia_tram) 4)
    (= (rate_metro) 300)
    (= (rate_bus) 20)
    (= (rate_bici) 3)
    (= (rate_tram) 120)
)
(:goal (and (>= (persone_trasportate) 5000)))
)
