(define (problem p19) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 8)
    (= (piste_ciclabili) 10)
    (= (fermate) 3)
    (= (personale_atm) 6)
    (= (persone_trasportate) 200)
    (= (soglia_metro) 500)
    (= (soglia_bus) 10)
    (= (soglia_bici) 10)
    (= (soglia_tram) 4)
    (= (rate_metro) 2000)
    (= (rate_bus) 35)
    (= (rate_bici) 20)
    (= (rate_tram) 70)
)
(:goal (and (>= (persone_trasportate) 2000)))
)
