(define (problem p12) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 50)
    (= (soglia_bus) 2)
    (= (soglia_bici) 1)
    (= (soglia_tram) 3)
    (= (rate_metro) 200)
    (= (rate_bus) 12)
    (= (rate_bici) 6)
    (= (rate_tram) 30)
)
(:goal (and (>= (persone_trasportate) 100)))
)
