(define (problem p18) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 80)
    (= (soglia_bus) 60)
    (= (soglia_bici) 40)
    (= (soglia_tram) 30)
    (= (rate_metro) 1000)
    (= (rate_bus) 80)
    (= (rate_bici) 25)
    (= (rate_tram) 400)
)
(:goal (and (>= (persone_trasportate) 50000)))
)
