(define (problem p07) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 20)
    (= (soglia_bus) 15)
    (= (soglia_bici) 10)
    (= (soglia_tram) 8)
    (= (rate_metro) 200)
    (= (rate_bus) 20)
    (= (rate_bici) 10)
    (= (rate_tram) 100)
)
(:goal (and (>= (persone_trasportate) 5000)))
)
