(define (problem p15) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 20)
    (= (soglia_bus) 15)
    (= (soglia_bici) 10)
    (= (soglia_tram) 12)
    (= (rate_metro) 150)
    (= (rate_bus) 30)
    (= (rate_bici) 15)
    (= (rate_tram) 80)
)
(:goal (and (>= (persone_trasportate) 10000)))
)
