(define (problem p16) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 5)
    (= (piste_ciclabili) 3)
    (= (fermate) 4)
    (= (personale_atm) 4)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 30)
    (= (soglia_bus) 5)
    (= (soglia_bici) 3)
    (= (soglia_tram) 5)
    (= (rate_metro) 400)
    (= (rate_bus) 20)
    (= (rate_bici) 10)
    (= (rate_tram) 90)
)
(:goal (and (>= (persone_trasportate) 3000)))
)
