(define (problem p05) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 10)
    (= (soglia_bus) 10)
    (= (soglia_bici) 8)
    (= (soglia_tram) 5)
    (= (rate_metro) 50)
    (= (rate_bus) 5)
    (= (rate_bici) 3)
    (= (rate_tram) 30)
)
(:goal (and (>= (persone_trasportate) 500)))
)
