(define (problem p17) (:domain traffico)
(:objects )
(:init
    (= (binari) 1)
    (= (corsie) 1)
    (= (piste_ciclabili) 1)
    (= (fermate) 1)
    (= (personale_atm) 1)
    (= (persone_trasportate) 50)
    (= (soglia_metro) 2)
    (= (soglia_bus) 2)
    (= (soglia_bici) 2)
    (= (soglia_tram) 2)
    (= (rate_metro) 3)
    (= (rate_bus) 2)
    (= (rate_bici) 1)
    (= (rate_tram) 4)
)
(:goal (and (>= (persone_trasportate) 300)))
)
