(define (problem p20) (:domain traffico)
(:objects )
(:init
    (= (binari) 0)
    (= (corsie) 0)
    (= (piste_ciclabili) 0)
    (= (fermate) 0)
    (= (personale_atm) 0)
    (= (persone_trasportate) 0)
    (= (soglia_metro) 1000)
    (= (soglia_bus) 500)
    (= (soglia_bici) 200)
    (= (soglia_tram) 300)
    (= (rate_metro) 5000)
    (= (rate_bus) 200)
    (= (rate_bici) 50)
    (= (rate_tram) 1000)
)
(:goal (and (>= (persone_trasportate) 1000000)))
)
